version: "3"

volumes:
  seyana-database:
    driver: local

services:
  db:
    container_name: seyana-db
    image: postgres:14.6
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: seyana
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    volumes:
      - type: volume
        source: seyana-database
        target: /var/lib/postgresql/data
